### ISSUE TITLE
C/ASM aPLib decompressor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [subz3ro-altair/at2#17]
```
Not really an issue, but here are usable sources of aPLib 0.26 decompressor.
Both C and compact ASM.

```

Original issue reported on code.google.com by `pissmasterplus` on 15 Apr 2014 at 6:31

Attachments:
* [aPlib_0.26.zip](https://storage.googleapis.com/google-code-attachments/at2/issue-17/comment-0/aPlib_0.26.zip)

**Comment by subz3ro-altair** [comment]
not applicable since ver. 2.3.55 / 2.4.22
